allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - envio-darwin-arm64@3.5.1-svm-alpha.2
  - envio-darwin-x64@3.5.1-svm-alpha.2
  - envio-linux-arm64@3.5.1-svm-alpha.2
  - envio-linux-x64-musl@3.5.1-svm-alpha.2
  - envio-linux-x64@3.5.1-svm-alpha.2

onlyBuiltDependencies:
  - esbuild
